### PR TITLE
Antiunification/common subexpression enumeration experiments in Lakeroad egglog(/Churchroad)

### LINKED ISSUE #385: Deduplicate sub-expressions/sub-circuits in design (antiunification?)

### LINKED ISSUE #392: Convert Yosys Lakeroad backend to output to new egglog syntax
Convert from language in `lakeroad.egg` to language in `lakeroad-antiunify.egg`

### LINKED ISSUE #393: Create a "load Lakeroad" function that loads Lakeroad DSL into an `EGraph`
Ideally this would be doable via an `include`, but I'm not sure that'll be possible as long as we have custom primitives that need to be added via Rust.

### LINKED ISSUE #395: Generate module enumeration rewrites programmatically
They're just a similar pattern repeated over and over again. Could write code to generate them automatically.

### PR DESCRIPTION
**Pull request by gussmith23**
Introduces a new IR for Lakeroad which allows for deduplication of "modules" -- i.e. sub-circuits that appear in multiple places in the graph. This is highly related to the idea of "antiunification", which I'm familiar with via the [babble paper](https://cseweb.ucsd.edu/~npolikarpova/publications/popl23.pdf). It's also the idea I proposed in my generals talk/thesis proposal in Spring 2023 and represents one of the core ideas I'm trying to explore with Churchroad/the work that follows Lakeroad.

Closes #393  
Closes #392
Closes #385 
Closes #395

### CODE REVIEW

**Comment by gussmith23** [comment]
@thiskappaisgrey  you may want to take a look at this PR -- I'm going to be switching things over to the new syntax defined in `lakeroad-antiunify.egg` soon! Most things won't change -- just a bit of syntax changes with respect to how you write down Ops. I've also updated the Yosys Lakeroad backend accordingly, so that should still just work. But eventually (perhaps in this PR) I will overwrite lakeroad.egg with the contents of lakeroad-antiunify.egg.

At a deeper level, this PR will likely enable things that are of interest to you. Namely, finding common patterns across a large design. It's specifically the `module-enumeration` rewrites that do this. These are a bit opaque at the moment, but they're generated by this function:
https://github.com/uwsampl/lakeroad/pull/386/files#diff-17558bab51e5a05e740401ae10beb48b7ec0397c6e251cf65862159153bf5abcR359
and they're tested here:
https://github.com/uwsampl/lakeroad/pull/386/files#diff-4730dcb986b7ef55932d372d4457ca6ad887cecc0a000deb23e63fc38dbf13f6R215

**Comment by thiskappaisgrey** [comment]
> @thiskappaisgrey you may want to take a look at this PR -- I'm going to be switching things over to the new syntax defined in `lakeroad-antiunify.egg` soon! Most things won't change -- just a bit of syntax changes with respect to how you write down Ops. I've also updated the Yosys Lakeroad backend accordingly, so that should still just work. But eventually (perhaps in this PR) I will overwrite lakeroad.egg with the contents of lakeroad-antiunify.egg.
> 
> At a deeper level, this PR will likely enable things that are of interest to you. Namely, finding common patterns across a large design. It's specifically the `module-enumeration` rewrites that do this. These are a bit opaque at the moment, but they're generated by this function: https://github.com/uwsampl/lakeroad/pull/386/files#diff-17558bab51e5a05e740401ae10beb48b7ec0397c6e251cf65862159153bf5abcR359 and they're tested here: https://github.com/uwsampl/lakeroad/pull/386/files#diff-4730dcb986b7ef55932d372d4457ca6ad887cecc0a000deb23e63fc38dbf13f6R215

Thanks! I'll take a look over the break!

**Comment by thiskappaisgrey** [comment]
Also, for reproducability - you should also commit `Cargo.lock` @gussmith23 . I got an error (no `egglog::constraint` ) when trying to build b/c of egglog version issues.

**Comment by gussmith23** [comment]
Great catch, thank you!!

**Comment by thiskappaisgrey** [comment]
@gussmith23 I think the core lakeroad language, the typing stuff, and the antiunification stuff should be separated into different files. I know it doesn't matter since declaring rewrite-rules doesn't actually run them - but I think you should have 1 file where it defines the minimal language that `lakeroad-yosys` outputs and the "extensions" in some other file. Mainly because the other stuff might not be relevant to my research - but I'd like to have a reference to the minimal lang that `lakeroad-yosys` will output and add my own extensions to that lang to fit what I'm trying to do. For example: https://github.com/thiskappaisgrey/research-stuff/blob/main/egg-rewrite-exp/egglog_src/lang.egg - I basically want to add this file (or something similar) as a source of truth for the `lakeroad-yosys` egg output - everything that the `lakeroad-yosys` egg backend outputs will be defined in this file and nothing more. Then, different ppl can add different "extensions" to the lang depending on what they are doing (by including their own rules after including the `lang.egg` file).

If I wanted typing ( https://github.com/thiskappaisgrey/research-stuff/blob/main/egg-rewrite-exp/egglog_src/typing.egg ), I would just do:
```
(include "lang.egg")
(include "typing.egg")
```
etc. I might not necessarily want to include typing (or the antiunification stuff). I think that just makes it a bit cleaner + more extendable rather than having everything in 1 file.

**Comment by gussmith23** [comment]
This has been moved to the Churchroad repo:
https://github.com/uwsampl/lakeroad/pull/386

**Pull request closed without merging**
